# 利用GitHub Action自定义定时任务
# https://docs.github.com/cn/actions
name: Xidian_DailyUp
on :
  schedule:
  - cron : '15,30 22,4,10 * * *'
  #UTC时间，分别对应了北京时间的6点、12点、18点的15分和30分

jobs:
  sign_in:
    runs-on: ubuntu-latest
    # 定义系统类型，这里选择Ubuntu
    steps:
    - name: '[Prepare] Code Check'
      uses: actions/checkout@v2
    # 从该仓库clone代码到虚拟机
    - name: '[Prepare] Set python'
      uses: actions/setup-python@v1
    # 安装python
      with:
        python-version: '3.x'
    - name: '[Prepare] Install Dependencies'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests
    # 安装需要的python库
    - name: '[Final Main] Check In'
      run: |
        python MainFunc.py
    # 执行代码
